# Инструкция настройки (RUS)

# 1. Поставьте "enable: true", чтобы включить нужные вам события.
# 2. Выберите тип команды "type: console" или "type: player"
# 3. Введите команды в "commands: ...", которые будут выполняться

# Чтобы добавить ник игрока, скачайте PlaceHolderAPI, и установите расширение "Player", через команду "/papi ecloud download Player".
# После этого используйте %player_name%, для отображение ника игрока.
# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# Setup instructions (ENG)

# 1. Set "enable: true" to enable the events you want.
# 2. Choose command type "type: console" or "type: player"
# 3. Enter the commands in the "commands: ..." that will be executed

# To add a player nickname, download the PlaceHolderAPI, and install the "Player" extension, via the command "/papi ecloud download Player".
# After that, use %player_name%, to display the player's nickname.

events:
  join:
    enable: true
    type: console
    commands:
      - 'say Добро пожаловать на увлекательный сервер! На сервере установлен плагин Commands at Join от MegaMaster684.'
      - 'say Пожалуйста, перейдите в "plugins/Commands-at-Join/config.yml" и настройте плагин.'
  quit:
    enable: false
    type: console
    commands:
      - ''
  change-world:
    enable: false
    type: console
    commands:
      - ''
  death:
    enable: false
    type: console
    commands:
      - ''
  break-block:
    enable: false
    type: console
    commands:
      - ''
  place-block:
    enable: false
    type: console
    commands:
      - ''
  player-click:
    enable: false
    type: console
    commands:
      - ''

messages:
  commandsList: "&7[&eCommands at Join&7] &fДоступные команды: &b/cj setup &fи &b/cj reload"
  reloadPlugin: "&7[&eCommands at Join&7] &aПлагин успешно перезагружен."
  noPermission: "&7[&eCommands at Join&7] &cУ вас нет прав на использование этой команды."