name: Commands-at-Join
main: me.megamaster684.commandsjoin.CommandsJoin
version: ${project.version}
description: Executes commands when joining the server, leaving the server, and other events.
api-version: 1.13
author: MegaMaster684
softdepend: [PlaceholderAPI]
commands:
  cj: {}